# Generated by Django 3.1 on 2020-12-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fourth_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products'),
        ),
    ]
