# Generated by Django 3.1 on 2020-12-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0002_auto_20201205_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fourth_image',
        ),
    ]
