# Generated by Django 3.1 on 2020-11-27 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0003_blogcategory_position_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('position_index', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='position_index',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=30)),
                ('position_index', models.IntegerField(null=True)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='OPG_Plac.productcategory')),
            ],
        ),
    ]
