# Generated by Django 3.1 on 2020-12-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0003_remove_product_fourth_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
