# Generated by Django 3.1 on 2020-12-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0004_auto_20201206_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=435),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=67),
        ),
    ]
