# Generated by Django 3.1 on 2020-11-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0005_auto_20201127_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seo_url', models.SlugField(unique=True)),
                ('item_id', models.SlugField(unique=True)),
                ('product_image', models.URLField()),
                ('second_image', models.URLField(blank=True)),
                ('third_image', models.URLField(blank=True)),
                ('fourth_image', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='OPG_Plac.productcategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='OPG_Plac.productsubcategory')),
            ],
        ),
    ]
