# Generated by Django 3.1 on 2020-12-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0006_auto_20201208_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Marko', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Pavić', max_length=150),
            preserve_default=False,
        ),
    ]
