# Generated by Django 3.1 on 2020-11-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0007_auto_20201128_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_img',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
