# Generated by Django 3.1 on 2020-11-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0008_auto_20201129_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
