# Generated by Django 3.1 on 2020-12-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0008_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'Blog categories'},
        ),
        migrations.AlterModelOptions(
            name='productavailability',
            options={'verbose_name_plural': 'Product availabilities'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product categories'},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'verbose_name_plural': 'Product subcategories'},
        ),
    ]
