# Generated by Django 3.1 on 2020-12-21 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0011_company_differentdelivery_userextended'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=20)),
                ('same_delivery', models.BooleanField(default=True)),
                ('delivery_first_name', models.CharField(blank=True, max_length=100)),
                ('delivery_last_name', models.CharField(blank=True, max_length=150)),
                ('delivery_address', models.CharField(blank=True, max_length=200)),
                ('delivery_post_code', models.CharField(blank=True, max_length=5)),
                ('delivery_phone', models.CharField(blank=True, max_length=20)),
                ('need_R1', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_address', models.CharField(blank=True, max_length=200)),
                ('company_post_code', models.CharField(blank=True, max_length=5)),
                ('OIB', models.CharField(blank=True, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('item_name', models.CharField(max_length=67, null=True)),
                ('item_seo_url', models.SlugField(null=True)),
                ('item_id', models.SlugField(null=True)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OPG_Plac.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='OPG_Plac.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='paymentOption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OPG_Plac.paymentoption'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OPG_Plac.orderstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
