# Generated by Django 3.1 on 2020-12-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0013_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notice',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
