# Generated by Django 3.1 on 2020-12-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0014_order_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='differentdelivery',
            name='delivery_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='place',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userextended',
            name='place',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
