# Generated by Django 3.1 on 2020-12-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0015_auto_20201221_1744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExtended',
            new_name='Extended',
        ),
    ]
