# Generated by Django 3.1 on 2020-12-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0016_auto_20201221_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='differentdelivery',
            name='user',
        ),
        migrations.AddField(
            model_name='extended',
            name='OIB',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='extended',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='extended',
            name='company_post_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='extended',
            name='conpany_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='extended',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='extended',
            name='delivery_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='extended',
            name='delivery_last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='extended',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='extended',
            name='delivery_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='extended',
            name='delivery_post_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='DifferentDelivery',
        ),
    ]
