# Generated by Django 3.1 on 2020-12-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0017_auto_20201221_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extended',
            old_name='conpany_address',
            new_name='company_address',
        ),
    ]
