# Generated by Django 3.1 on 2020-12-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0018_auto_20201221_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extended',
            old_name='has_company',
            new_name='need_R1',
        ),
    ]
