# Generated by Django 3.1 on 2020-12-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0019_auto_20201221_1858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extended',
            new_name='ExtendedUser',
        ),
    ]
