# Generated by Django 3.1.2 on 2020-12-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0020_auto_20201221_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_id',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(default='', max_length=67),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=99, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_seo_url',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
