# Generated by Django 3.1.2 on 2020-12-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0021_auto_20201222_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentoption',
            old_name='option',
            new_name='name',
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='reference',
            field=models.CharField(default='', max_length=4, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_seo_url',
            field=models.SlugField(max_length=120),
        ),
    ]
