# Generated by Django 3.1.2 on 2020-12-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0023_paymentoption_tooltip'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentoption',
            name='descriptive_name',
            field=models.CharField(default='change', max_length=100),
            preserve_default=False,
        ),
    ]
