# Generated by Django 3.1.2 on 2020-12-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0024_paymentoption_descriptive_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='OPG_Plac.order'),
        ),
    ]
