# Generated by Django 3.1.2 on 2020-12-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0025_auto_20201223_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OPG_Plac.orderstatus'),
        ),
    ]
