# Generated by Django 3.1.2 on 2020-12-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPG_Plac', '0026_auto_20201224_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
